---
abstract: 'Simple ORMapper Plugin For Nephia'
author:
  - 'mackee <macopy123[attttt]gmai.com>'
build_requires:
  DBD::SQLite: 0
  File::Spec: 0
  File::Temp: 0
  HTTP::Request::Common: 0
  JSON: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.3, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nephia-Plugin-Teng
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Nephia::Plugin::Teng:
    file: lib/Nephia/Plugin/Teng.pm
    version: 0.01
requires:
  DBI: 0
  Nephia: 0.29
  Nephia::DSLModifier: 0
  Teng: 0.18
  perl: 5.008005
resources:
  bugtracker: https://github.com/mackee/Nephia-Plugin-Teng/issues
  homepage: https://github.com/mackee/Nephia-Plugin-Teng
  repository: git://github.com/mackee/Nephia-Plugin-Teng.git
version: 0.01
x_contributors:
  - 'mackee <macopy123@gmail.com>'
